# Generated by Django 5.1.8 on 2026-04-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chatbotuser_invalid_input_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotuser',
            name='preset_state',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('awaiting_menstruating', 'Awaiting Menstruating Answer'), ('awaiting_last_period_date', 'Awaiting Last Period Date'), ('awaiting_has_ttd', 'Awaiting Has TTD Answer'), ('awaiting_reminder_hour', 'Awaiting Reminder Hour'), ('completed', 'Completed'), ('calendar_awaiting_last_period', 'Calendar Awaiting Last Period Date')], default='not_started', max_length=64),
        ),
    ]
